### ISSUE TITLE
Any Region Changer ModMii Edition

### ISSUE THREAD

**Issue by larsenv** [OpenShopChannel/Apps#12]
https://github.com/modmii/Any-Region-Changer-ModMii-Edition/releases/latest
Peripherals: Wii Remote
Category: Utilities

**Comment by GabubuAvailable** [comment]
This homebrew app is used ONLY if you want to region change the Wii. I think we need to wait for XFlak's confirmation first!

**Comment by GabubuAvailable** [comment]
> I don't mind it being available on the OSC, in fact it could/should replace other older region changing apps in my opinion

~ XFlak

**Comment by dhtdht020** [comment]
why was this closed?

**Comment by dhtdht020** [comment]
the only quote I see is one supporting the addition of this app?

**Comment by GabubuAvailable** [comment]
I understood now. I'll go make a PR
