### ISSUE TITLE
Cave Story Wii Port (CSE2)

### ISSUE THREAD

**Issue by autumn-mnya** [OpenShopChannel/Apps#14]
https://autumn-mnya.github.io/games/cavestorywii/files/cavestorywii.zip

Peripherals: 1 Wii Remote, 1 Wii Classic Controller, 1 GameCube Controller, SD
Category: Game

Name should be either "Cave Story" or "CSE2".
Author name can be listed as autumn_mnya.

Long description: This is a port of Cave Story to the wii, built off of CSE2, a decompilation of Cave Story's freeware version.

**Comment by dhtdht020** [comment]
Very cool. Just making sure, is this something that is okay to distribute? Does this not include copyrighted assets?

**Comment by autumn-mnya** [comment]
This is based on the freeware version, so it doesn't contain copyrighted assets. The cave story community has also come to the conclusion that distribution binaries of it is okay as well.

**Comment by dhtdht020** [comment]
The freeware version's assets are not copyrighted?

**Comment by autumn-mnya** [comment]
No..?

If they were, why would they be uploaded on [cavestory.org](https://www.cavestory.org/download/cave-story.php)?

Not to mention the dozens of mods releasing the assets + nxengine using them, it's fine. Cave Story+'s updated graphics/music is a problem though --> Which should not be uploading and isn't in this.

**Comment by dhtdht020** [comment]
I think this is a very cool project and I do want it in, but I hope you do understand this is an area Open Shop Channel has to be careful about, and there are things we cannot do without some investigation first, which is the purpose of this conversation.

I am not familiar with the specifics of the Cave Story scene or community, and I need clarification on these subjects.

I can see that Cave Story Engine 2, which this is supposedly based on, was DMCA'd once before. I can also see that this [switch port](https://apps.fortheusers.org/switch/CSE2) on Homebrew App Store seems concerned about that.

Is the DMCA relevant to these assets?

**Comment by dhtdht020** [comment]
I am less concerned about the binary, I need consensus on the assets.

**Comment by autumn-mnya** [comment]
Incredibly late response to this.

The doukutsu-rs project has the freeware game data in its own [repo](https://github.com/doukutsu-rs/game-data), and it's perfectly fine because it isn't new content added in the Cave Story+ releases of the game.

The freeware assets are fine to redistribute. Cave Story+ assets (which arent used by this port) would need to be grabbed by the user.

**Comment by larsenv** [comment]
@Artuto is this gonna be merged

**Comment by autumn-mnya** [comment]
This has been updated to have 4 player local co-op, along with mod support and 6 default built-in mods to go along with the base game.

It supports 4 Wii Remotes, 4 GameCube controllers, and 4 Classic Controllers.

Regarding content --> It doesn't contain any of the upscaled graphics used in re-releases of Cave Story released by nicalis such as Cave Story+ for PC, Cave Story+ for switch, and Cave Story wiiware. Same goes for the soundtrack, it only contains the original "Organya" soundtrack.

This port is based off of the decompilation project --> CSE2, which was DMCA-d by nicalis a couple years back.

The Cave Story community specifically has figured out that it seems to be okay to upload binaries of CSE2, but preferably not the source code usually. You can see multiple CSE2 ports released without the source code --> Such as the [vita port](https://github.com/IruzzArcana/CSE2-vita), the [java port](https://doukutsuclub.knack.com/database#index/mod-details/636cc3fc414fa10021505eb2/), or many of the [CSE2 related mod releases](https://doukutsuclub.knack.com/database#tag-definitions/tag-details/5c8ed1971c4e8853238cecd2/).

It should be fine to upload this port to Open Shop Channel, but its up to others whether or not it should be put on the shop channel. I just think it'd be pretty nice to have this version of Cave Story more accessible to others, is all.

Hope this makes sense, and that is all.

**Comment by Artuto** [comment]
Can you confirm if this supports Wii Mini and vWii?

**Comment by playerjmr** [comment]
> Can you confirm if this supports Wii Mini and vWii?

i dont doubt it wouldnt work on either of those, unless it specifically only supported gamecube controllers, which appears to not be the case
