### ISSUE TITLE
Lots of apps show as 01 Jan 1970 on Homebrew Browser

### ISSUE THREAD

**Issue by larsenv** [OpenShopChannel/Apps#21]
I don't know where to put this, but many of the apps on the Homebrew Browser show that date, why?

**Comment by Naim2000** [comment]
Because their release date tag fucking sucked
![image](https://github.com/OpenShopChannel/Apps/assets/44107089/3ed1deca-5e27-4153-9830-8f24fec0a294)

**Comment by larsenv** [comment]
Saw that already, it was humorous, but could it parse by the last modified date?

**Comment by larsenv** [comment]
Plus the ones which are correct could be inaccurate.

**Comment by dhtdht020** [comment]
Apps with an invalid release date have a release date of "0", we cannot use file modifications dates for technical reasons.
