### ISSUE TITLE
GC-anim-wii

### ISSUE THREAD

**Issue by larsenv** [OpenShopChannel/Apps#7]
https://github.com/supertazon/GC-anim-Wii
Peripherals: Wii Remote(?)
Category: Utilities(?)

**Comment by GabubuAvailable** [comment]
I mean people can use it but most of them don't think that they need to dump the GameCube's BIOS and read the [README's "How To Install"](https://github.com/supertazon/GC-anim-Wii#how-to-install) part... 
P.S.: My opinion btw

**Comment by emilydaemon** [comment]
I don't think this would be fit for distribution on OSC since it requires files from the GameCube's BIOS, which would be illegal to redistribute.
I also don't think there's an icon.png or a meta.xml... In my opinion, this issue should be closed for now.

**Comment by Naim2000** [comment]
There are lots(not really) of games on OSC that require you to rip original files from elsewhere, don't think that's changed so far
Lack of icon though? Mmm

**Comment by GabubuAvailable** [comment]
It also has icon and meta @emilydaemon

**Comment by emilydaemon** [comment]
Ah, I hadn't looked at the .rar. My bad.

> There are lots(not really) of games on OSC that require you to rip original files from elsewhere [...]

Is there any reason for a manifest not being written yet? If not, I could take on that task.

**Comment by dhtdht020** [comment]
not interested in adding any more applications that require manual tinkering through a desktop computer to get working, and the ones that are already there should be removed (except maybe, space cadet pinball, it's quite popular and there are videos on how to get it working).

**Comment by Naim2000** [comment]
Oh. Fair

**Comment by GabubuAvailable** [comment]
Fair enough

**Comment by dhtdht020** [comment]
by "applications that require manual tinkering through a desktop computer to get working", I particularly mean applications that we cannot distribute in a functional state because they require copyrighted resources the user has to provide themselves.

these make no sense to distribute. zero sense.

**Comment by GabubuAvailable** [comment]
So... We can close this issue as not planned right?

**Comment by dhtdht020** [comment]
Assistance in finding and removing such applications currently available on the Open Shop Channel will be greatly appreciated.

**Comment by Naim2000** [comment]
Super mario war was the first one to come to mind (as well as space cadet pinball but MJD video)

**Comment by emilydaemon** [comment]
Super Mario War doesn't require you to tinker with a computer to get it to work, it works out of the box.
Well, at least that was the case when I downloaded it.

**Comment by BENDER-V2** [comment]
where would we post apps that we find that need manual setup through a computer / copy righted assets?
